#define MATERIAL_ALTERATION_NONE 0
#define MATERIAL_ALTERATION_NAME 1
#define MATERIAL_ALTERATION_DESC 2
#define MATERIAL_ALTERATION_COLOR 4
#define MATERIAL_ALTERATION_ALL (~MATERIAL_ALTERATION_NONE)
#define PLASTEEL_COLOUR "#8e9799"
#define MATERIAL_STEEL "steel"
#define MATERIAL_PLASTEEL "plasteel"
